version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - SHARP_IGNORE_GLOBAL_LIBVIPS=true && npm install
  build:
    commands:
#      - aws s3 sync s3://alfie76589/images ./images --exclude="*.gpx" --exclude="*.mp4"
      - npm run build-legacy
  post_build:
    commands:
      - aws s3 sync public s3://gatsby-src