version: 0.2
env:
  variables:
    NODE_OPTIONS: "--openssl-legacy-provider"
    SHARP_IGNORE_GLOBAL_LIBVIPS: true
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20.11.1
      - npm install -g gatsby-cli@4.20.0
  pre_build:
    commands:
      - npm install
      - aws s3 sync s3://alfie76589/images ./images --exclude="*.gpx" --exclude="*.mp4"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://mountain-dog.co.uk --recursive
      - aws s3 sync public s3://mountain-dog.co.uk
      - aws cloudfront create-invalidation --distribution-id E3RXWJELGM9KA0 --paths "/*"
cache:
  paths:
    - node_modules/
    - ~/.npm
    - images/