version: 0.2
env:
  variables:
    NODE_OPTIONS: "--openssl-legacy-provider"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 20.11.1
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - node --version
      - rm -rf node_modules && SHARP_IGNORE_GLOBAL_LIBVIPS=true
      - rm -f package-lock.json
      - npm cache clean --force
      - npm rebuild --verbose sharp
      - npm install
#      - aws s3 sync s3://alfie76589/images ./images --exclude="*.gpx" --exclude="*.mp4"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync public s3://gatsby-src

cache:
  paths:
    - node_modules/
    - ~/.npm
    - images/