version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - n 16.0.0
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - node --version
      - rm -rf node_modules && SHARP_IGNORE_GLOBAL_LIBVIPS=true
      - rm -f package-lock.json
      - npm cache clean --force
      - npm rebuild --verbose sharp
      - npm install
#      - aws s3 sync s3://alfie76589/images ./images --exclude="*.gpx" --exclude="*.mp4"
  build:
    commands:
      - npm run build-legacy
  post_build:
    commands:
      - aws s3 sync public s3://gatsby-src